# Generated by Django 6.0.2 on 2026-02-07 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_alter_table_options_table_table_type_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='booking',
            name='bookings_bo_booking_fa13ed_idx',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='table',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
        migrations.DeleteModel(
            name='Table',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
